; File autogenerated by build-queries-nvim.py; do not edit

(comment) @comment

; FIXME: shebang
; (shebang_recipe
;     (shebang
;         interpreter:(TEXT) @language)
;     (shebang_body) @content
; )

(source_file
    ; (item (setting lang:(identifier) @language))
    (item (recipe (recipe_body) @content))
)
; If no shell is explicitly set, let's default to bash for recipe bodies
; (source_file
;   (item (recipe (recipe_body) @injection.content))
;   (#set! injection.include-children)
;   (#set! injection.language "bash"))

; (interpolation (expression) @just)

